// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDQrdberX-SgOIpsprZoLj2o-UBKGUOwTk',
    appId: '1:907376373345:web:6d2bc726c54638ba9b0420',
    messagingSenderId: '907376373345',
    projectId: 'senior-fitness-app',
    authDomain: 'senior-fitness-app.firebaseapp.com',
    storageBucket: 'senior-fitness-app.firebasestorage.app',
    measurementId: 'G-GE3DPP411G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDJcaz3XX5mRtMMmE-QKUExwdmkkvjws2o',
    appId: '1:907376373345:android:ef64104971b6a5bb9b0420',
    messagingSenderId: '907376373345',
    projectId: 'senior-fitness-app',
    storageBucket: 'senior-fitness-app.firebasestorage.app',
  );

}